node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool 'sonarScanner';
    withSonarQubeEnv() {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }


  stage ('Quality Gate'){
    timeout(time: 5, unit: 'MINUTES') {
                script {
                    def qg = waitForQualityGate()
                    if (qg.status != 'OK') {
                        error "Pipeline aborted due to a quality gate failure: ${qg.status}"
                    }
                }
            }

  }
  stage('secrect search'){
    sh "trufflehog  --no-update --json filesystem . > ./../jenkins-setting/result.txt"
    sh "bash ./jenkins-setting/script.sh"
}
stage('build'){
        sh 'python3 setup.py sdist'
    }

    stage('publish'){
      sh 'pip install twine'
        sh 'twine upload -r nexus dist/*'
    }
}